// <auto-generated />
using System;
using CodeFrame.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFrame.Models.Migrations
{
    [DbContext(typeof(CodeFrameContext))]
    [Migration("20180703055617_vicky")]
    partial class vicky
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CodeFrame.Models.DbModel.Button", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BtnClass")
                        .HasMaxLength(50);

                    b.Property<string>("BtnIcon")
                        .HasMaxLength(50);

                    b.Property<string>("BtnName")
                        .HasMaxLength(20);

                    b.Property<int>("BtnPosition");

                    b.Property<string>("BtnScript")
                        .HasMaxLength(50);

                    b.Property<string>("BtnTip")
                        .HasMaxLength(50);

                    b.Property<string>("BtnUrl")
                        .HasMaxLength(300);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser");

                    b.Property<int?>("CreateUserId");

                    b.Property<string>("DisplayCondition")
                        .HasMaxLength(500);

                    b.Property<int>("EditType");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsSpecial");

                    b.Property<int>("MenuId");

                    b.Property<int>("OrderBy");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<string>("SpName")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser");

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("t_sysButton");
                });

            modelBuilder.Entity("CodeFrame.Models.DbModel.Column", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ColumnName")
                        .HasMaxLength(30);

                    b.Property<int?>("ColumnType");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser");

                    b.Property<int?>("CreateUserId");

                    b.Property<string>("DataOptions")
                        .HasMaxLength(300);

                    b.Property<int?>("DisplayType");

                    b.Property<int?>("FkTableId");

                    b.Property<bool>("IsIndexed");

                    b.Property<bool>("IsShow");

                    b.Property<int>("OrderBy");

                    b.Property<string>("ReMark");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<string>("ShowName")
                        .HasMaxLength(20);

                    b.Property<int?>("TableId");

                    b.Property<string>("Tip")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser");

                    b.Property<int?>("UpdateUserId");

                    b.Property<int?>("Width");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("t_sysColumn");
                });

            modelBuilder.Entity("CodeFrame.Models.DbModel.DepartMent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser");

                    b.Property<int?>("CreateUserId");

                    b.Property<string>("DptName")
                        .HasMaxLength(20);

                    b.Property<bool>("IsActive");

                    b.Property<int>("OrderBy");

                    b.Property<int>("ParentId");

                    b.Property<string>("ReMark");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser");

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("t_sysDepartMent");
                });

            modelBuilder.Entity("CodeFrame.Models.DbModel.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser");

                    b.Property<int?>("CreateUserId");

                    b.Property<bool>("IsActive");

                    b.Property<string>("MenuIcon");

                    b.Property<string>("MenuName")
                        .HasMaxLength(20);

                    b.Property<string>("MenuUrl")
                        .HasMaxLength(500);

                    b.Property<int>("OrderBy");

                    b.Property<int?>("ParentMenuId");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<int?>("SubSystemId");

                    b.Property<int?>("SysTableId");

                    b.Property<int?>("TableId");

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser");

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.HasIndex("SubSystemId");

                    b.HasIndex("TableId");

                    b.ToTable("t_sysMenuInfo");
                });

            modelBuilder.Entity("CodeFrame.Models.DbModel.RoleInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser");

                    b.Property<int?>("CreateUserId");

                    b.Property<string>("Describe")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<bool>("IsActive");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser");

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("t_sysRoleInfo");
                });

            modelBuilder.Entity("CodeFrame.Models.DbModel.RolePower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ButtonId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser");

                    b.Property<int?>("CreateUserId");

                    b.Property<int>("MentId");

                    b.Property<int>("RoleId");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<int>("Type");

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser");

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("t_sysRolePower");
                });

            modelBuilder.Entity("CodeFrame.Models.DbModel.SubSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser");

                    b.Property<int?>("CreateUserId");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Link");

                    b.Property<int>("OrderBy");

                    b.Property<string>("ReMark");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<string>("SystemIcon");

                    b.Property<string>("SystemName");

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser");

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("t_sysSubSystem");
                });

            modelBuilder.Entity("CodeFrame.Models.DbModel.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser");

                    b.Property<int?>("CreateUserId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsMultiple");

                    b.Property<bool>("IsPaging");

                    b.Property<int>("OrderBy");

                    b.Property<string>("ReMark");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<string>("ShowName");

                    b.Property<string>("TableName");

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser");

                    b.Property<int?>("UpdateUserId");

                    b.HasKey("Id");

                    b.ToTable("t_sysTable");
                });

            modelBuilder.Entity("CodeFrame.Models.DbModel.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("CreateUser");

                    b.Property<int?>("CreateUserId");

                    b.Property<int?>("DepartMentId");

                    b.Property<string>("Describe")
                        .HasMaxLength(500);

                    b.Property<int?>("Gender");

                    b.Property<string>("Group")
                        .HasMaxLength(100);

                    b.Property<string>("GroupNum")
                        .HasMaxLength(100);

                    b.Property<bool>("IsActive");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(11);

                    b.Property<string>("Picture")
                        .HasMaxLength(300);

                    b.Property<string>("Post")
                        .HasMaxLength(300);

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken();

                    b.Property<string>("Skill")
                        .HasMaxLength(100);

                    b.Property<string>("TrueName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("UpdateUser");

                    b.Property<int?>("UpdateUserId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("DepartMentId");

                    b.ToTable("t_sysUserInfo");
                });

            modelBuilder.Entity("CodeFrame.Models.DbModel.UserRole", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("t_sysUserRole");
                });

            modelBuilder.Entity("Microsoft.EntityFrameworkCore.AutoHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Changed");

                    b.Property<DateTime>("Created");

                    b.Property<int>("Kind");

                    b.Property<string>("RowId")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("AutoHistory");
                });

            modelBuilder.Entity("CodeFrame.Models.DbModel.Button", b =>
                {
                    b.HasOne("CodeFrame.Models.DbModel.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CodeFrame.Models.DbModel.Column", b =>
                {
                    b.HasOne("CodeFrame.Models.DbModel.Table", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableId");
                });

            modelBuilder.Entity("CodeFrame.Models.DbModel.Menu", b =>
                {
                    b.HasOne("CodeFrame.Models.DbModel.SubSystem", "SubSystem")
                        .WithMany("MenuInfo")
                        .HasForeignKey("SubSystemId");

                    b.HasOne("CodeFrame.Models.DbModel.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");
                });

            modelBuilder.Entity("CodeFrame.Models.DbModel.UserInfo", b =>
                {
                    b.HasOne("CodeFrame.Models.DbModel.DepartMent", "DepartMent")
                        .WithMany("UserInfos")
                        .HasForeignKey("DepartMentId");
                });

            modelBuilder.Entity("CodeFrame.Models.DbModel.UserRole", b =>
                {
                    b.HasOne("CodeFrame.Models.DbModel.RoleInfo", "RoleInfo")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CodeFrame.Models.DbModel.UserInfo", "UserInfo")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
